# Generated by Django 3.0.5 on 2020-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200801_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.IntegerField(),
        ),
    ]
